Repository fga-eps-mds/2019.1-Aix, pull requests merged in 2019-03, with the labels that each got.

#21 Adicionando documento de metodologias
  _site/docs/METODOLOGIAS.md
Labels: Documentation, EPS, Methodology

#20 Issue 10 tap
  _site/docs/TAP.md
Labels: Documentation, EPS

#23 Adicionando arquivo de fluxograma com a versão 1.0
  _site/docs/FLUXOGRAMA.md
  _site/images/fluxograma_Versao_1.0.png
Labels: Documentation, EPS

#25 Issue 12 definir tecnologias
  _site/docs/GCS.md
Labels: Architecture, Documentation, EPS

#27 Issue 17 documento de arquitetura
  docs/DOCUMENTO_DE_ARQUITETURA.md
Labels: Architecture, Documentation, MDS

#48 #15 - Adicionando o diagrama de fluxo e movendo os documentos para p…
  _site/docs/DOCUMENTO_DE_ARQUITETURA.md
  _site/docs/VISION_DOCUMENT.md
  _site/images/Diagrama de Fluxo.png
Labels: Architecture, EPS
