Repository fga-eps-mds/2019.1-Aix, pull requests merged in 2019-04, with the labels that each got.

#54 Adicionando Canvas do Projeto
  _site/docs/CANVAS.md
  _site/images/canvas.jpg
Labels: Documentation, EPS

#89 Issue 29 roadmap
  .env
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  _posts/2019-04-06-roadmap-projeto
  _site/assets/img/RoadMap_release1.png
  _site/assets/img/RoadMap_release2.png
  analytics/replay.Dockerfile
  analytics/replay.py
  analytics/setup_elastic.py
  bot/Makefile
  bot/actions/actions.py
  bot/connector.py
  bot/data/intents/actions.md
  bot/data/intents/catalog.md
  bot/data/intents/main.md
  bot/data/stories/catalog.md
  bot/data/stories/main.md
  bot/domain.yml
  bot/endpoints.yml
  bot/fallback.py
  bot/nlu_config.yml
  bot/policy_config.yml
  bot/requirements.txt
  bot/run-rocketchat.py
  bot/tracker_store.py
  bot/train.py
  bot/validator.py
  docker-compose-dev.yml
  docker-compose.yml
  docker/actions.Dockerfile
  docker/actions.requirements.txt
  docker/bot.Dockerfile
  docker/notebooks.Dockerfile
  notebooks/intents/.ipynb_checkpoints/intents-analysis-checkpoint.ipynb
  notebooks/intents/intents-analysis.ipynb
  notebooks/stories/.ipynb_checkpoints/stories-analysis-checkpoint.ipynb
  notebooks/stories/img/.keep
  notebooks/stories/stories-analysis.ipynb
  scripts/bot_config.py
  services/actions/__init__.py
  services/actions/actions.py
  services/api/Dockerfile-dev
  services/api/manage.py
  services/api/project/__init__.py
  services/api/project/config.py
  services/api/requirements.txt
  services/core/config/endpoints.yml
  services/core/data/nlu.md
  services/core/data/stories.md
  services/core/domain.yml
Labels: Documentação, EPS

#139 Issue 78 refatorar doc arquitetura
  _posts/2019-03-29-documento-de-arquitetura.md
  assets/img/Diagrama de Fluxo.png
  assets/img/diagrama_de_fluxo.png
Labels: Arquitetura, Documentação, EPS, Refatoração

#172 Issue 128 criar nfr
  _posts/2019-04-20-NFR.md
  assets/img/nfr.jpg
Labels: Arquitetura, Documentação, EPS, bot

#240 [HOTFIX] - Arquivos sendo checados que não deveriam arrumado.
  .codeclimate.yml
Labels: bug

#243 [HOTFIX] - Colocando badges no readme e arrumando bug no codeclimate.
  .codeclimate.yml
  README.md
Labels: bug
