Repository fga-eps-mds/2019.1-Aix, pull requests merged in 2019-05, with the labels that each got.

#253 Issue 207 conteudos referentes a vetor
  .travis.yml
  actions/actions.Dockerfile
  bot/data/intents/conteudo_extra.md
  bot/data/intents/exemplo.md
  bot/data/intents/exercicio.md
  bot/data/intents/main.md
  bot/data/intents/sobre.md
  bot/data/stories/conteudo_extra.md
  bot/data/stories/exemplo.md
  bot/data/stories/exercicio.md
  bot/data/stories/full_path.md
  bot/data/stories/sobre.md
  bot/domain.yml
  docker/bot.Dockerfile
Labels: DevOps, bug

#271 Issue 234 configurar e testar
  .coveragerc
  .coveralls.yml
  .travis.yml
  bot/requirements.txt
  setup.py
  tests/__init__.py
  tests/test_fallback.py
Labels: Testes

#273 Resolvendo bugs do log do Travis
  .coveragerc
  .travis.yml
  bot/Makefile
  bot/__init__.py
  docker/bot.Dockerfile
  tests/test_fallback.py
Labels: bug

#329 Issue 313 atualizar arquitetura
  docs/_posts/2019-03-29-documento-de-arquitetura.md
  docs/_posts/2019-04-05-backlog-de-produto.md
  docs/assets/img/diagrama_de_fluxo.png
  notebooks/intents/.ipynb_checkpoints/intents-analysis-checkpoint.ipynb
  notebooks/intents/intents-analysis.ipynb
  notebooks/stories/.ipynb_checkpoints/stories-analysis-checkpoint.ipynb
  notebooks/stories/img/.keep
  notebooks/stories/stories-analysis.ipynb
Labels: Arquitetura, Documentação, EPS
